export type Tramite = {
  id: string;
  embarcacion_id: string;
  broker_id: string | null;
  operador_comercial_id: string | null;
  operador_tecnico_id: string | null;
  estado: string;
  fecha_creacion: string | null;
  fecha_presentacion: string | null;
  fecha_estado_actual: string | null;
  prioridad_tipo: string | null;
  prioridad_fecha_objetivo: string | null;
  total_pactado: number | null;
  saldo: number | null;
  activo: boolean | null;
  created_at: string | null;
  dependencia_id: string | null;
  subsanacion_lista: boolean | null;
  prioridad_provisorio: boolean | null;
  listo_para_presentar: boolean | null;
  numero_gde: string | null;
  numero_tramite: string | null;
  motivo_cambio_estado: string | null;
  prioridad_matricula: boolean | null;
  provisorio_solicitado: boolean | null;
  tipo_tramite_id: string | null;
  listo_para_repartir: boolean | null;
  lugar_guarda_actual: string | null;
  busqueda: string | null;
  dependencia_sugerida_id: string | null;
  dependencia_is: string | null;
  fecha_listo_para_presentar: string | null;
  fecha_provisorio: string | null;
  decha_presentacion: string | null; // ojo: parece typo en DB
  fecha_finalizacion: string | null;
  firmo_autorizacion: boolean | null;
  dejo_arba: boolean | null;
  observaciones: string | null;
  nueva_embarcacion_id: string | null;
};